// Auto-generated by convertMdToData.cjs — do not edit manually
// Run: npm run convert

export interface Quote {
  phase: "before" | "mid" | "after" | "walkback" | "undercut" | "note";
  date: string;
  text: string;
  sourceUrl: string;
  context?: string;
}

export interface NarrativeEntry {
  id: string;
  name: string;
  title: string;
  subtitle?: string;
  category: string;
  quotes: Quote[];
  shiftSummary: string;
}

export interface NarrativeSection {
  id: string;
  title: string;
  entries: NarrativeEntry[];
}

export const narrativeSections: NarrativeSection[] = [
  {
    "id": "overview",
    "title": "Overview",
    "entries": [
      {
        "id": "lindsey-graham",
        "name": "Lindsey Graham",
        "title": "Senator (R-SC)",
        "category": "overview",
        "quotes": [
          {
            "phase": "note",
            "date": "Feb 28, Wall Street Journal",
            "text": "\"If there are deaths or injuries in this operation, I can say without hesitation that they sacrificed for a noble cause, a safer America and a more just world. The operation will be massive in scope and has as its goal the elimination of the regime as demanded by the people of Iran.\"",
            "sourceUrl": "https://www.thedailybeast.com/trumps-top-suck-up-says-iran-war-is-worth-americans-dying-for/"
          },
          {
            "phase": "note",
            "date": "Mar 1, Meet the Press",
            "text": "\"That's not our job, to pick the next Iranian government. We're not going to occupy the country. No boots on the ground. You know this idea, 'you break it, you own it?' I don't buy that one bit.\" When pressed: \"How many times do I have to tell you?! Our job is to make sure Iran is no longer the largest state sponsor of terrorism.\"",
            "sourceUrl": "https://www.mediaite.com/media/news/how-many-times-do-i-have-to-tell-you-lindsey-graham-snaps-at-nbcs-kristen-welker-asking-if-trump-has-a-plan-on-iran/"
          },
          {
            "phase": "note",
            "date": "Mar 4",
            "text": "\"This is a religious war….What we’re facing right now is a moment and decision that will set the course of the future of the Mid East for a thousand years.”",
            "sourceUrl": "https://x.com/Ahmed_hassan_za/status/2029268569716855029?s=20"
          },
          {
            "phase": "note",
            "date": "Mar 8",
            "text": "“Our allies in Israel have shown amazing capability when it comes to collapsing the murderous regime in Iran. America is most appreciative. However, there will be a day soon that the Iranian people will be in charge of their own fate, not the murderous ayatollah’s regime. In that regard, please be cautious about what targets you select. Our goal is to liberate the Iranian people in a fashion that does not cripple their chance to start a new and better life when this regime collapses. The oil economy of Iran will be essential to that endeavor.”",
            "sourceUrl": "https://x.com/kenklippenstein/status/2030816428803108870/photo/1",
            "context": "https://www.rawstory.com/iran-2675868092/"
          }
        ],
        "shiftSummary": "Regime elimination → not our job → holy war → protect the oil"
      },
      {
        "id": "josh-hawley",
        "name": "Josh Hawley",
        "title": "Senator (R-MO)",
        "category": "overview",
        "quotes": [
          {
            "phase": "note",
            "date": "Mar 3",
            "text": "Voted no on war powers.",
            "sourceUrl": "https://missouriindependent.com/briefs/missouris-josh-hawley-defends-trumps-iran-strike-rejects-war-powers-vote/"
          },
          {
            "phase": "note",
            "date": "Mar 3, post-classified briefing",
            "text": "\"Personally, I would hope for a very swift conclusion, but I don't know if that's going to be the case.\" Described the operation as \"quite large,\" \"rapidly, rapidly evolving\" and \"really almost changing by the hour.\"",
            "sourceUrl": "https://www.pbs.org/newshour/world/live-updates-trump-says-iran-war-could-last-weeks"
          }
        ],
        "shiftSummary": "Voted to let the war continue after describing it as massive and open-ended"
      }
    ]
  },
  {
    "id": "democrats-in-congress",
    "title": "DEMOCRATS in CONGRESS",
    "entries": [
      {
        "id": "chuck-schumer",
        "name": "Chuck Schumer",
        "title": "Senate Minority Leader (D-NY)",
        "category": "democrats-in-congress",
        "quotes": [
          {
            "phase": "note",
            "date": "Feb 28",
            "text": "\"The administration has not provided Congress and the American people with critical details about the scope and immediacy of the threat. The administration must brief Congress.\"",
            "sourceUrl": "https://www.npr.org/2026/02/28/nx-s1-5730203/iran-israel-trump-congress-strikes-reaction"
          },
          {
            "phase": "note",
            "date": "Mar 4",
            "text": "“I left the intelligence briefing more concerned than reassured…If the case for war were strong, it would be consistent. Instead, the rationales change by the hour.”",
            "sourceUrl": "https://www.ap7am.com/en/121790/trumps-iran-strike-ignites-capitol-hill-fight"
          },
          {
            "phase": "note",
            "date": "Mar 4",
            "text": "\"Today every senator — every single one — will pick a side: Do you stand with the American people who are exhausted with forever wars in the Middle East or stand with Donald Trump and Pete Hegseth as they bumble us headfirst into another war?\"",
            "sourceUrl": "https://www.thetimes.com/world/middle-east/article/iran-latest-news-trump-us-middle-east-wgnsdjdlz#:~:text=The%20vote%20fell%20mostly%20along,us%20headfirst%20into%20another%20war?%E2%80%9D"
          },
          {
            "phase": "note",
            "date": "Mar 4",
            "text": "\"Before you can feel satisfied about a supplemental [funding package] — and I haven't seen it — you have to know what the real goals are and what the end game is.\"",
            "sourceUrl": "https://wbhm.org/npr-story/a-split-senate-votes-against-measure-to-constrain-trumps-authorities-in-iran/#:~:text=Y.%2C%20said%20he%20would%20not%20comment%20on,and%20what%20the%20end%20game%20is.%E2%80%9D%20Sen"
          }
        ],
        "shiftSummary": "Forced a war powers vote, left funding on the table"
      },
      {
        "id": "chris-coons",
        "name": "Chris Coons",
        "title": "Senator (D - DE)",
        "category": "democrats-in-congress",
        "quotes": [
          {
            "phase": "note",
            "date": "Feb 28",
            "text": "“I am praying for the safety of our service members and the many civilians in the Middle East in harm’s way today. President Trump’s military campaign against Iran and call for regime change are the beginning of a reckless new war of choice with no clear strategy and no clear endpoint. This is not how a democracy goes to war. Less than five years after the end of the longest war in American history, the United States is once again staring down another open-ended conflict with a hostile country in the Middle East that could cost the lives of many American service members. This is not a limited, defensive strike, but rather a full-throated declaration of war that does not clearly serve the interests of or reflect the wishes of the American people.”",
            "sourceUrl": "https://www.coons.senate.gov/news/press-releases/senator-coons-statement-on-iran-strikes/"
          },
          {
            "phase": "note",
            "date": "Mar 4",
            "text": "Senate floor speech after vote: \"We should be careful about opening a door into chaos in the Middle East when we cannot see the other side of it.\"",
            "sourceUrl": "https://www.militarytimes.com/news/pentagon-congress/2026/03/05/senate-republicans-vote-down-legislation-to-halt-iran-war/"
          },
          {
            "phase": "note",
            "date": "Mar 3",
            "text": "On funding, Coons said he expected a supplemental request and said he \"will continue to support our troops and to make sure we are making all the investments we can to keep them and their families safe.\" Said an open hearing is required for supplemental funding.",
            "sourceUrl": "https://www.npr.org/2026/03/04/nx-s1-5735867/war-powers-congress-iran"
          }
        ],
        "shiftSummary": "\"Reckless new war of choice,” but left door open for further funding"
      },
      {
        "id": "mark-kelly",
        "name": "Mark Kelly",
        "title": "Senator (D-AZ)",
        "category": "democrats-in-congress",
        "quotes": [
          {
            "phase": "note",
            "date": "Feb 28, press release",
            "text": "“After promising to keep America out of war and instead focus on lowering costs for families, Donald Trump has launched a large-scale military operation against Iran. We’ve seen this playbook before. Weeks of inflated claims, selective facts, and talk of imminent threats that led the American people into a war that cost thousands of American lives and trillions of taxpayer dollars.”",
            "sourceUrl": "https://www.kelly.senate.gov/newsroom/press-releases/kelly-statement-on-military-operation-against-iran/"
          },
          {
            "phase": "note",
            "date": "",
            "text": "Mar 1, Meet the Press",
            "sourceUrl": "https://x.com/atrupar/status/2028134866454303056?s=20"
          },
          {
            "phase": "note",
            "date": "Mar 4",
            "text": "Mark Kelly voted Yes on the war powers resolution",
            "sourceUrl": "https://www.youtube.com/shorts/FrmMajT_ci0"
          }
        ],
        "shiftSummary": "Tepid on war powers"
      },
      {
        "id": "tim-kaine",
        "name": "Tim Kaine",
        "title": "Senator (D-VA)",
        "subtitle": "Led war powers effort",
        "category": "democrats-in-congress",
        "quotes": [
          {
            "phase": "note",
            "date": "Feb 28, NPR",
            "text": "\"This is important. The lives of our troops are at risk. We ought to come back to Washington right away to vote on this.\" and \"The Constitution says we're not supposed to be at war without a vote of Congress.\" Co-authored the War Powers Resolution to halt the operation entirely.",
            "sourceUrl": "https://www.npr.org/2026/02/28/nx-s1-5730228/sen-tim-kaine-calls-on-the-senate-to-vote-on-the-war-powers-resolution"
          },
          {
            "phase": "note",
            "date": "Mar 4, after the War Powers vote failed",
            "text": "\"Nobody gets to hide and give the president an easy pass or an end-run around the Constitution. Everybody's got to declare whether they're for this war or against it.\"",
            "sourceUrl": "https://www.pbs.org/newshour/politics/watch-live-senate-expected-to-vote-on-war-powers-resolution-after-u-s-israeli-strikes-on-iran"
          },
          {
            "phase": "note",
            "date": "Mar 7",
            "text": "on supplemental funding, Kaine said: \"until they send us something and we see what the details are, I'm not going to commit one way or the other on a bill I haven't seen...I'm going to do everything I can to stop this illegal and unwise war\"",
            "sourceUrl": "https://x.com/bluevirginia/status/2030305939815866671"
          }
        ],
        "shiftSummary": "Led the war powers fight, won't say no to funding."
      },
      {
        "id": "elissa-slotkin",
        "name": "Elissa Slotkin",
        "title": "Senator (D-MI)",
        "category": "democrats-in-congress",
        "quotes": [
          {
            "phase": "note",
            "date": "Feb 28, press release",
            "text": "\"Issues of war and peace should be treated with the utmost consequence. And President Trump hasn't made his case to the American people. He hasn't laid out the goals or the imminent threat posed by Iran that justifies risking a wider regional war. And he hasn't followed the Constitution and brought this issue before Congress before committing our nation to war.\"",
            "sourceUrl": "https://www.slotkin.senate.gov/2026/02/28/slotkin-statement-on-u-s-military-action-against-iran/"
          },
          {
            "phase": "note",
            "date": "Mar 4, Politico",
            "text": "On supplemental funding, Slotkin said: \"I need to know the goals and the plan… I don't rule anything out. I mean, we're in it.\"",
            "sourceUrl": "https://www.meidasplus.com/p/today-in-politics-bulletin-321-3526"
          }
        ],
        "shiftSummary": "\"He hasn't made his case\" → \"we're in it.\""
      },
      {
        "id": "gary-peters",
        "name": "Gary Peters",
        "title": "Senator (D-MI)",
        "category": "democrats-in-congress",
        "quotes": [
          {
            "phase": "note",
            "date": "Feb 28",
            "text": "\"The President just acknowledged he is risking American lives by dragging us into another \"war\" in the Middle East, without Congress' approval. Our Constitution requires this check for a reason. The American people don't want to send their sons and daughters to another unjustified forever war across the world. Iran is a bad actor and we must ensure they never produce nuclear weapons. We had a diplomatic agreement with Iran on nuclear proliferation and President Trump withdrew during his first term without a plan for what comes next because he was playing petty politics. Now, he's sending American servicemembers back to the Middle East to attempt to fix the problems he created. The Administration must immediately brief Congress on these strikes and its next steps, end goal, and strategy to ensure this protects, not weakens, our homeland security.\"",
            "sourceUrl": "https://x.com/SenGaryPeters/status/2027765104905752588?s=20"
          },
          {
            "phase": "note",
            "date": "Mar 3, Axios",
            "text": "On supplemental funding, Peters said:\"Let's wait. Let's play one step at a time. Let's deal with the War Powers first.\"",
            "sourceUrl": "https://www.axios.com/2026/03/03/senate-democrats-iran-war-funding"
          }
        ],
        "shiftSummary": "\"Unjustified forever war\" → \"let's deal with War Powers first\" → hasn't ruled out funding"
      },
      {
        "id": "peter-aguilar",
        "name": "Peter Aguilar",
        "title": "Representative (D-CA)",
        "subtitle": "House Democratic Caucus Chair",
        "category": "democrats-in-congress",
        "quotes": [
          {
            "phase": "note",
            "date": "Mar 4, Washington Times",
            "text": "\"The details matter. We need to look at what portion of this goes to munitions, does this degrade our readiness if we don't support this? These are all questions that committees of jurisdiction… will all kind of dig in once they send this over.\"",
            "sourceUrl": "https://www.washingtontimes.com/news/2026/mar/4/lawmakers-await-white-house-request-defense-funds-iran-war/"
          },
          {
            "phase": "note",
            "date": "Mar 5, Press Release",
            "text": "“Donald Trump campaigned on being the president of peace. Instead, he has only proven himself to be the president of broken promises. He promised to lower costs on day one. He promised to root out corruption. He promised to fight for working people. And he promised to always put America first. He lied. On every single measure, he has not only turned his back on the Americans who put their faith in him, he has made life harder, more dangerous and more expensive for them…How is it that Republicans can find billions of dollars for bombs and billionaires, but not a cent to bring down costs for the American people?...As the people’s representatives, Democrats stood against this war in Congress today and we will continue fighting to protect our service members and put an end to this seemingly endless conflict. And at the end of the day, it is Donald Trump and Republicans who will have to answer to the American people.” About: The Over Under is a Tide Loop project. Reach out here to add more.",
            "sourceUrl": "https://democrats.house.gov/newsroom/press-releases/statement-from-chairman-aguilar-on-the-bipartisan-iran-war-powers-resolution"
          }
        ],
        "shiftSummary": "keeps the door open for funding while strongly critical of war"
      }
    ]
  },
  {
    "id": "2028-democratic-contenders",
    "title": "2028 DEMOCRATIC CONTENDERS",
    "entries": [
      {
        "id": "gavin-newsom",
        "name": "Gavin Newsom",
        "title": "Governor of California",
        "subtitle": "Top 2028 Democratic presidential contender",
        "category": "2028-democratic-contenders",
        "quotes": [
          {
            "phase": "note",
            "date": "Feb 28, X post",
            "text": "\"The corrupt and repressive Iranian regime must never have nuclear weapons. The leadership of Iran must go. But that does not justify the President of the United States engaging in an illegal, dangerous war that will risk the lives of our American service members and our friends without justification to the American people. President Trump is putting Americans at risk abroad because he is unpopular at home. As this unfolds, California stands with the Iranian-American community in our state, recognizing they have many friends and loved ones who have fought bravely to chart their own future to end decades of state violence and denial of basic rights.\"",
            "sourceUrl": "https://x.com/CAgovernor/status/2027777089643151661"
          },
          {
            "phase": "note",
            "date": "Mar 3, Hayward CA press conference",
            "text": "\" We have American planes that have literally been shot down by American allies. We have to reconcile why our bombs were used or Israeli bombs were used to kill children, young girls, at a school, and what the imminent threat was. Four service members died today, and Donald Trump spent more time talking about his ballroom than he did talking about the loss of those lives.\"",
            "sourceUrl": "https://abc7news.com/post/newsom-iran-war-trump-ballroom-service-members/16078823/"
          },
          {
            "phase": "note",
            "date": "Mar 4, Pod Save America live",
            "text": "Newsom blamed Netanyahu directly for pushing the U.S. into war. He called for reconsidering all U.S. military aid to Israel. He suggested Israel could \"appropriately\" be described as an apartheid state.",
            "sourceUrl": "https://us.cnn.com/2026/03/04/politics/gavin-newsom-israel"
          },
          {
            "phase": "note",
            "date": "Mar 5, NYT",
            "text": "“Asked to clarify the comments, Izzy Gardon, a spokesperson for Newsom, said the governor ‘believes in Israel’s right to exist — and its right to defend itself. Period.’ He added that ‘the governor is calling out a difficult truth,’ blaming President Donald Trump and Netanyahu for ‘taking Israel down a course that threatens the safety of Israel — a democracy and America’s closest Middle East ally — as well as Israelis and American Jews.’”",
            "sourceUrl": "https://www.nytimes.com/2026/03/04/us/politics/gavin-newsom-israel.html",
            "context": "https://gvwire.com/2026/03/05/newsom-compares-israel-to-apartheid-state-questions-military-support/"
          }
        ],
        "shiftSummary": "Anti-war → apartheid state → spokesman walked it back the next morning"
      },
      {
        "id": "ruben-gallego",
        "name": "Ruben Gallego",
        "title": "Senator (D-AZ)",
        "subtitle": "Iraq War veteran; 2028 contender",
        "category": "2028-democratic-contenders",
        "quotes": [
          {
            "phase": "note",
            "date": "Feb 28, press release",
            "text": "\"I watched brave young men die in Iraq for a mission that was never clearly justified to the American people. I came home carrying the weight of that war, and I live with PTSD every single day. President Trump promised no more forever wars. Instead, he has illegally dragged us into another one without congressional authorization and no long-term strategy.\"",
            "sourceUrl": "https://www.gallego.senate.gov/news/press-releases/statement-senator-gallego-on-president-trumps-illegal-war-with-iran/"
          },
          {
            "phase": "note",
            "date": "Mar 3, X / Roll Call",
            "text": "\"When the bill comes to pay for the replenishment of interceptors and munitions, the middle eastern countries that we have been protecting need to pay for it. We aren't cutting more Medicaid, food stamps for protecting these countries in a war of choice and not in our interest.\"",
            "sourceUrl": "https://rollcall.com/2026/03/03/iran-war-triggers-talk-of-supplemental-defense-funding/"
          },
          {
            "phase": "note",
            "date": "Mar 4, CNN with Kaitlan Collins",
            "text": "Implied he'd vote to fund the war if Gulf states cover at least 50% of costs. \"I want to see at least 50% of that money has to come from the Gulf States and from Israel. We're using our stockpile. We're using our taxpayer money to protect those countries. At the same time, we're cutting Medicaid, we're cutting food stamps.\"",
            "sourceUrl": "https://www.mediaite.com/media/tv/democratic-senator-says-hed-vote-to-fund-trumps-dumb-war-with-iran/"
          }
        ],
        "shiftSummary": "Illegal war → would fund it if Gulf states pay half"
      }
    ]
  },
  {
    "id": "international-eu",
    "title": "INTERNATIONAL / EU",
    "entries": [
      {
        "id": "mark-carney",
        "name": "Mark Carney",
        "title": "Prime Minister of Canada",
        "subtitle": "Won snap election partly on anti-Trump sovereignty platform",
        "category": "international-eu",
        "quotes": [
          {
            "phase": "note",
            "date": "Feb 28, statement from Mumbai",
            "text": "\"Canada supports the United States acting to prevent Iran from obtaining a nuclear weapon and to prevent its regime from further threatening international peace and security.\" Also: \"We have not been party to the military buildup to this or the military planning of this, so it is not envisioned that we would be part of it.\"",
            "sourceUrl": "https://globalnews.ca/news/11715023/carney-iran-war-support-australia/"
          },
          {
            "phase": "note",
            "date": "Mar 3–4, Sydney / Lowy Institute",
            "text": "Carney says his support for the attack on Iran is “not a blank cheque.” “We [Canada] were not informed in advance. We were not asked to participate. Prima facie, it appears that these actions are inconsistent with international law.”",
            "sourceUrl": "https://www.cbc.ca/news/politics/carney-iran-war-9.7112616"
          }
        ],
        "shiftSummary": "Strong support → \"not a blank cheque\""
      },
      {
        "id": "keir-starmer",
        "name": "Keir Starmer",
        "title": "UK Prime Minister",
        "subtitle": "Host of US bases",
        "category": "international-eu",
        "quotes": [
          {
            "phase": "note",
            "date": "Feb 28",
            "text": "“The United Kingdom played no role in these strikes. But we have long been clear – the regime in Iran is utterly abhorrent.…That is the route to de-escalation and back to the negotiating table.”",
            "sourceUrl": "https://www.gov.uk/government/speeches/pm-statement-on-iran-28-february-2026"
          },
          {
            "phase": "note",
            "date": "Before Mar 1",
            "text": "The UK government initially refused use of their bases in support of Iran. Starmer’s comments imply that UK government lawyers were not certain that the US / Israeli strikes were done in accordance with international law.",
            "sourceUrl": "https://www.chathamhouse.org/2026/03/uk-arguments-us-operations-its-bases-blur-line-between-lawful-self-defence-and-unlawful-war"
          },
          {
            "phase": "note",
            "date": "Mar 2",
            "text": "\"Iran is pursuing a scorched earth strategy, so we are supporting the collective self-defense of our allies and our people in the region.\" Starmer authorized the use of British bases by the U.S. military.",
            "sourceUrl": "https://www.stripes.com/theaters/europe/2026-03-02/uk-us-bases-iran-20928006.html"
          },
          {
            "phase": "note",
            "date": "Mar 2",
            "text": "\"I want to be very clear: We all remember the mistakes of Iraq. And we have learned those lessons.\"",
            "sourceUrl": "https://www.stripes.com/theaters/europe/2026-03-02/uk-us-bases-iran-20928006.html"
          }
        ],
        "shiftSummary": "No bases → bases, cited Iraq."
      }
    ]
  }
];

export const allCategories: string[] = ["overview","democrats-in-congress","2028-democratic-contenders","international-eu"];
